export { default as IconNodejs } from '../../../assets/svg/nodejs-original.svg'
export { default as IconExpress } from '../../../assets/svg/express-original.svg'
export { default as IconPhp } from '../../../assets/svg/php-original.svg'
export { default as IconLaravel } from '../../../assets/svg/laravel-plain.svg'
export { default as IconExpo } from '../../../assets/svg/expo-original.svg'
export { default as IconReact } from '../../../assets/svg/react-original.svg'
export { default as IconRedux } from '../../../assets/svg/redux-original.svg'
export { default as IconAngular } from '../../../assets/svg/angularjs-original.svg'
export { default as IconMongodb } from '../../../assets/svg/mongodb-original-wordmark.svg'
export { default as IconPostgresql } from '../../../assets/svg/postgresql-original.svg'
export { default as IconMysql } from '../../../assets/svg/mysql-original.svg'
export { default as IconDocker } from '../../../assets/svg/docker-original.svg'
export { default as IconLinux } from '../../../assets/svg/linux-original.svg'

export { default as IconVscode } from '../../../assets/svg/vscode-original.svg'
export { default as IconGit } from '../../../assets/svg/git-original.svg'
export { default as IconGithub } from '../../../assets/svg/github-original.svg'